    name: Build and Push Next.js Docker Image

    on:
      push:
        branches:
          - main # Trigger on pushes to the main branch
      workflow_dispatch: # Allow manual triggering

    jobs:
      build-and-push:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Log in to GitHub Container Registry
            uses: docker/login-action@v3
            with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }} # Use the built-in GITHUB_TOKEN

          - name: Build and push Docker image
            uses: docker/build-push-action@v5
            with:
              context: . # Path to your Dockerfile context (usually the root of your repo)
              push: true
              tags: ghcr.io/${{ github.repository }}:latest # Tag the image with your repo name and 'latest'
